import Navbar from '@/components/Header'
import './globals.css'
import { Roboto_Slab } from 'next/font/google'
import { InitialPageLoad } from '@/components/InitialPageLoad'

const inter = Roboto_Slab({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full`}>
        <InitialPageLoad>
          <Navbar />
          {children}
        </InitialPageLoad>
      </body>
    </html>
  )
}
